"""add workflow retrieval identity

Revision ID: d815c00eb002
Revises: e8d0f8f5919c
Create Date: 2026-07-12 14:21:28.020412
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d815c00eb002"
down_revision: str | Sequence[str] | None = "e8d0f8f5919c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parties",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('person', 'organization')", name=op.f("ck_parties_kind")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parties")),
    )
    op.execute(
        sa.text(
            """
            INSERT INTO parties (id, kind, display_name)
            SELECT DISTINCT
                (data->>'organization_party_id')::uuid,
                'organization',
                'Migrated organization ' || left(data->>'organization_party_id', 8)
            FROM workflow_events
            WHERE event_type = 'workflow_jobs_proposed'
              AND data ? 'organization_party_id'
            ON CONFLICT (id) DO NOTHING
            """
        )
    )
    op.execute(
        sa.text(
            """
            INSERT INTO parties (id, kind, display_name)
            SELECT
                md5(workflow.id::text || 'migrated_organization')::uuid,
                'organization',
                'Migrated organization ' || left(workflow.id::text, 8)
            FROM workflows AS workflow
            WHERE NOT EXISTS (
                SELECT 1
                FROM workflow_events AS event
                WHERE event.workflow_id = workflow.id
                  AND event.event_type = 'workflow_jobs_proposed'
                  AND event.data ? 'organization_party_id'
            )
            ON CONFLICT (id) DO NOTHING
            """
        )
    )
    op.execute(
        sa.text(
            """
            INSERT INTO parties (id, kind, display_name)
            SELECT DISTINCT
                actor_id::uuid,
                'person',
                'Migrated person ' || left(actor_id, 8)
            FROM workflow_events
            WHERE event_type = 'workflow_jobs_proposed'
              AND actor_type = 'party'
            ON CONFLICT (id) DO NOTHING
            """
        )
    )
    op.execute(
        sa.text(
            """
            INSERT INTO parties (id, kind, display_name)
            SELECT DISTINCT
                actor_id::uuid,
                'person',
                'Migrated person ' || left(actor_id, 8)
            FROM workflow_events
            WHERE event_type = 'workflow_created'
              AND actor_type = 'party'
              AND actor_id ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
            ON CONFLICT (id) DO NOTHING
            """
        )
    )
    op.create_table(
        "organization_memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("person_party_id", sa.UUID(), nullable=False),
        sa.Column("organization_party_id", sa.UUID(), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_party_id"],
            ["parties.id"],
            name=op.f("fk_organization_memberships_organization_party_id_parties"),
        ),
        sa.ForeignKeyConstraint(
            ["person_party_id"],
            ["parties.id"],
            name=op.f("fk_organization_memberships_person_party_id_parties"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_memberships")),
    )
    op.create_index(
        "uq_organization_memberships_current",
        "organization_memberships",
        ["person_party_id", "organization_party_id"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_table(
        "party_identifiers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("party_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["party_id"], ["parties.id"], name=op.f("fk_party_identifiers_party_id_parties")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_party_identifiers")),
    )
    op.create_index(
        "uq_party_identifiers_current_value",
        "party_identifiers",
        ["kind", "value"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    # Historical actor references are provenance, not current verification or
    # authority. Trusted bootstrap or identity provisioning must populate
    # identifiers, memberships, Participants, and roles explicitly.
    op.create_table(
        "workflow_participants",
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("party_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["party_id"], ["parties.id"], name=op.f("fk_workflow_participants_party_id_parties")
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("fk_workflow_participants_workflow_id_workflows"),
        ),
        sa.PrimaryKeyConstraint("workflow_id", "party_id", name=op.f("pk_workflow_participants")),
    )
    op.create_table(
        "workflow_participant_roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("party_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "role IN ('Broker', 'Reporter', 'Policyholder', 'Claimant')",
            name=op.f("ck_workflow_participant_roles_role"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id", "party_id"],
            ["workflow_participants.workflow_id", "workflow_participants.party_id"],
            name="fk_workflow_participant_roles_participant",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_participant_roles")),
    )
    op.create_index(
        "uq_workflow_participant_roles_current",
        "workflow_participant_roles",
        ["workflow_id", "party_id", "role"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.add_column("workflows", sa.Column("organization_party_id", sa.UUID(), nullable=True))
    op.execute(
        sa.text(
            """
            UPDATE workflows AS workflow
            SET organization_party_id =
                (event.data->>'organization_party_id')::uuid
            FROM workflow_events AS event
            WHERE event.workflow_id = workflow.id
              AND event.event_type = 'workflow_jobs_proposed'
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE workflows AS workflow
            SET organization_party_id =
                md5(workflow.id::text || 'migrated_organization')::uuid
            WHERE workflow.organization_party_id IS NULL
            """
        )
    )
    op.alter_column("workflows", "organization_party_id", nullable=False)
    op.create_foreign_key(
        "fk_workflows_organization_party", "workflows", "parties", ["organization_party_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_workflows_organization_party", "workflows", type_="foreignkey")
    op.drop_column("workflows", "organization_party_id")
    op.drop_index(
        "uq_workflow_participant_roles_current",
        table_name="workflow_participant_roles",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("workflow_participant_roles")
    op.drop_table("workflow_participants")
    op.drop_index(
        "uq_party_identifiers_current_value",
        table_name="party_identifiers",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("party_identifiers")
    op.drop_index(
        "uq_organization_memberships_current",
        table_name="organization_memberships",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("organization_memberships")
    op.drop_table("parties")
    # ### end Alembic commands ###
