"""create workflow protocol

Revision ID: e8d0f8f5919c
Revises:
Create Date: 2026-07-12 13:55:54.298123
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e8d0f8f5919c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflows",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("corrects_workflow_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'completed', 'cancelled')", name=op.f("ck_workflows_status")
        ),
        sa.CheckConstraint(
            "corrects_workflow_id IS NULL OR corrects_workflow_id <> id",
            name=op.f("ck_workflows_not_self_correction"),
        ),
        sa.ForeignKeyConstraint(
            ["corrects_workflow_id"], ["workflows.id"], name="fk_workflows_correction"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflows")),
    )
    op.create_table(
        "workflow_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("revises_job_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'succeeded' AND output IS NOT NULL) OR (status <> 'succeeded' AND output IS NULL)",
            name=op.f("ck_workflow_jobs_output_matches_status"),
        ),
        sa.CheckConstraint(
            "status IN ('waiting', 'queued', 'running', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_workflow_jobs_status"),
        ),
        sa.CheckConstraint(
            "attempts <= max_attempts", name=op.f("ck_workflow_jobs_attempt_budget")
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_workflow_jobs_attempts_nonnegative")),
        sa.CheckConstraint("max_attempts > 0", name=op.f("ck_workflow_jobs_max_attempts_positive")),
        sa.CheckConstraint(
            "revises_job_id IS NULL OR revises_job_id <> id",
            name=op.f("ck_workflow_jobs_not_self_revision"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id", "revises_job_id"],
            ["workflow_jobs.workflow_id", "workflow_jobs.id"],
            name="fk_workflow_jobs_revision",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"], ["workflows.id"], name="fk_workflow_jobs_workflow"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_jobs")),
        sa.UniqueConstraint("workflow_id", "id", name="uq_workflow_jobs_workflow_id_id"),
    )
    op.create_index(
        "ix_workflow_jobs_claim",
        "workflow_jobs",
        ["available_at", "created_at", "id"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_index(
        "uq_workflow_jobs_revises_job_id",
        "workflow_jobs",
        ["revises_job_id"],
        unique=True,
        postgresql_where=sa.text("revises_job_id IS NOT NULL"),
    )
    op.create_table(
        "workflow_job_dependencies",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("depends_on_job_id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "job_id <> depends_on_job_id",
            name=op.f("ck_workflow_job_dependencies_not_self_dependency"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id", "depends_on_job_id"],
            ["workflow_jobs.workflow_id", "workflow_jobs.id"],
            name="fk_workflow_job_dependencies_prerequisite",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id", "job_id"],
            ["workflow_jobs.workflow_id", "workflow_jobs.id"],
            name="fk_workflow_job_dependencies_job",
        ),
        sa.PrimaryKeyConstraint(
            "job_id", "depends_on_job_id", name=op.f("pk_workflow_job_dependencies")
        ),
    )
    op.create_index(
        "ix_workflow_job_dependencies_reverse",
        "workflow_job_dependencies",
        ["workflow_id", "depends_on_job_id"],
        unique=False,
    )
    op.create_table(
        "workflow_job_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("worker_id", sa.Text(), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("runtime_instance_id", sa.UUID(), nullable=True),
        sa.Column("application_build", sa.Text(), nullable=False),
        sa.Column("adapter_version", sa.Text(), nullable=True),
        sa.Column("provider_tool_version", sa.Text(), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'running' AND finished_at IS NULL AND result IS NULL) OR (status IN ('succeeded', 'failed') AND finished_at IS NOT NULL AND result IS NOT NULL) OR (status IN ('cancelled', 'abandoned') AND finished_at IS NOT NULL AND result IS NULL)",
            name=op.f("ck_workflow_job_runs_terminal_shape"),
        ),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed', 'cancelled', 'abandoned')",
            name=op.f("ck_workflow_job_runs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id", "job_id"],
            ["workflow_jobs.workflow_id", "workflow_jobs.id"],
            name="fk_workflow_job_runs_job",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_job_runs")),
        sa.UniqueConstraint(
            "workflow_id", "job_id", "id", name="uq_workflow_job_runs_workflow_job_id"
        ),
    )
    op.create_index(
        "ix_workflow_job_runs_lease",
        "workflow_job_runs",
        ["lease_expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_index(
        "uq_workflow_job_runs_running_job",
        "workflow_job_runs",
        ["job_id"],
        unique=True,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_table(
        "workflow_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("actor_type", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.Text(), nullable=False),
        sa.Column("cause_type", sa.Text(), nullable=False),
        sa.Column("cause_id", sa.Text(), nullable=False),
        sa.Column("approval_grant_id", sa.UUID(), nullable=True),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "run_id IS NULL OR job_id IS NOT NULL", name=op.f("ck_workflow_events_run_requires_job")
        ),
        sa.ForeignKeyConstraint(
            ["approval_grant_id"], ["workflow_events.id"], name="fk_workflow_events_approval_grant"
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id", "job_id", "run_id"],
            ["workflow_job_runs.workflow_id", "workflow_job_runs.job_id", "workflow_job_runs.id"],
            name="fk_workflow_events_run",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id", "job_id"],
            ["workflow_jobs.workflow_id", "workflow_jobs.id"],
            name="fk_workflow_events_job",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"], ["workflows.id"], name="fk_workflow_events_workflow"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_events")),
        sa.UniqueConstraint("workflow_id", "id", name="uq_workflow_events_workflow_id_id"),
    )
    op.create_index(
        "ix_workflow_events_job",
        "workflow_events",
        ["workflow_id", "job_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_workflow_events_run",
        "workflow_events",
        ["workflow_id", "run_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_workflow_events_timeline",
        "workflow_events",
        ["workflow_id", "occurred_at", "id"],
        unique=False,
    )
    op.create_index(
        "uq_workflow_events_approval_cause",
        "workflow_events",
        ["job_id", "cause_type", "cause_id"],
        unique=True,
        postgresql_where=sa.text("event_type = 'approval_granted'"),
    )
    op.create_index(
        "uq_workflow_events_approval_invalidation",
        "workflow_events",
        ["approval_grant_id"],
        unique=True,
        postgresql_where=sa.text("event_type = 'approval_invalidated'"),
    )
    op.create_index(
        "uq_workflow_events_dispatch_job",
        "workflow_events",
        ["job_id"],
        unique=True,
        postgresql_where=sa.text("event_type = 'external_effect_dispatch_started'"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("workflow_event_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("destination_type", sa.Text(), nullable=False),
        sa.Column("destination_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("claimed_by", sa.Text(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'queued' AND claimed_by IS NULL AND lease_expires_at IS NULL AND delivered_at IS NULL) OR (status = 'delivering' AND claimed_by IS NOT NULL AND lease_expires_at IS NOT NULL AND delivered_at IS NULL) OR (status = 'delivered' AND claimed_by IS NULL AND lease_expires_at IS NULL AND delivered_at IS NOT NULL) OR (status = 'failed' AND claimed_by IS NULL AND lease_expires_at IS NULL AND delivered_at IS NULL)",
            name=op.f("ck_notifications_delivery_shape"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'delivering', 'delivered', 'failed')",
            name=op.f("ck_notifications_status"),
        ),
        sa.CheckConstraint(
            "attempts <= max_attempts", name=op.f("ck_notifications_attempt_budget")
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_notifications_attempts_nonnegative")),
        sa.CheckConstraint("max_attempts > 0", name=op.f("ck_notifications_max_attempts_positive")),
        sa.ForeignKeyConstraint(
            ["workflow_id", "workflow_event_id"],
            ["workflow_events.workflow_id", "workflow_events.id"],
            name="fk_notifications_workflow_event",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"], ["workflows.id"], name="fk_notifications_workflow"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint(
            "workflow_event_id",
            "kind",
            "destination_type",
            "destination_id",
            name="uq_notifications_delivery",
        ),
    )
    op.create_index(
        "ix_notifications_claim",
        "notifications",
        ["available_at", "created_at", "id"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_index(
        "ix_notifications_lease",
        "notifications",
        ["lease_expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'delivering'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_notifications_lease",
        table_name="notifications",
        postgresql_where=sa.text("status = 'delivering'"),
    )
    op.drop_index(
        "ix_notifications_claim",
        table_name="notifications",
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.drop_table("notifications")
    op.drop_index(
        "uq_workflow_events_dispatch_job",
        table_name="workflow_events",
        postgresql_where=sa.text("event_type = 'external_effect_dispatch_started'"),
    )
    op.drop_index(
        "uq_workflow_events_approval_invalidation",
        table_name="workflow_events",
        postgresql_where=sa.text("event_type = 'approval_invalidated'"),
    )
    op.drop_index(
        "uq_workflow_events_approval_cause",
        table_name="workflow_events",
        postgresql_where=sa.text("event_type = 'approval_granted'"),
    )
    op.drop_index("ix_workflow_events_timeline", table_name="workflow_events")
    op.drop_index("ix_workflow_events_run", table_name="workflow_events")
    op.drop_index("ix_workflow_events_job", table_name="workflow_events")
    op.drop_table("workflow_events")
    op.drop_index(
        "uq_workflow_job_runs_running_job",
        table_name="workflow_job_runs",
        postgresql_where=sa.text("status = 'running'"),
    )
    op.drop_index(
        "ix_workflow_job_runs_lease",
        table_name="workflow_job_runs",
        postgresql_where=sa.text("status = 'running'"),
    )
    op.drop_table("workflow_job_runs")
    op.drop_index("ix_workflow_job_dependencies_reverse", table_name="workflow_job_dependencies")
    op.drop_table("workflow_job_dependencies")
    op.drop_index(
        "uq_workflow_jobs_revises_job_id",
        table_name="workflow_jobs",
        postgresql_where=sa.text("revises_job_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_workflow_jobs_claim",
        table_name="workflow_jobs",
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.drop_table("workflow_jobs")
    op.drop_table("workflows")
    # ### end Alembic commands ###
